#pragma once

#define DEBOUNCE 5

#define WEAR_LEVELING_LOGICAL_SIZE 4096
#define WEAR_LEVELING_BACKING_SIZE 8192
#define DYNAMIC_KEYMAP_MACRO_COUNT 32

#define MATRIX_ROWS  3
#define MATRIX_COLS  4

#define ENCODERS_PAD_A {B4, C15}
#define ENCODERS_PAD_B {B5, C14 }
#define ENCODER_RESOLUTIONS {4,4}

#define WS2812_DI_PIN B9
#define RGB_MATRIX_LED_COUNT 8  
